// Code generated by jtd-codegen for TypeScript v0.2.1

export interface RootOverrideTypeDiscriminatorBaz {
  foo: "baz";
}

export interface Root {
  override_elements_container: string[];
  override_type_discriminator: any;
  override_type_enum: any;
  override_type_expr: any;
  override_type_properties: any;
  override_values_container: { [key: string]: string };
}
