// Code generated by jtd-codegen for TypeScript v0.2.1

export type Root = string;

export type DefaultName = string;

export type Foo = string;

export type Foo0 = string;

export type Foo1 = string;

export type FooBar = string;

export type FooBar0 = string;

export type Foo0bar = string;

export type FooBar1 = string;
