// Code generated by jtd-codegen for Java + Jackson v0.2.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum RootFooBar {
    @JsonProperty("x")
    X,

    @JsonProperty("y")
    Y,
}
