// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package jtd_codegen_e2e

type Root = string

type DefaultName = string

type Foo = string

type Foo0 = string

type Foo1 = string

type FooBar = string

type FooBar0 = string

type Foo0bar = string

type FooBar1 = string
