#!/bin/bash

set -e

for schema in integration_tests/schemas/*; do
  mkdir -p integration_tests/rust/$(basename $schema .jtd.json)
  mkdir -p integration_tests/typescript/$(basename $schema .jtd.json)

  cargo run -- \
    --rust-out=integration_tests/rust/$(basename $schema .jtd.json) \
    --typescript-out=integration_tests/typescript/$(basename $schema .jtd.json) \
    -- $schema
done
