// Code generated by jtd-codegen for C# + System.Text.Json v0.2.0

using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    public class RootOverrideTypeDiscriminatorBaz : object
    {
        [JsonPropertyName("foo")]
        public string Foo { get => "baz"; }
    }
}
