# Code generated by jtd-codegen for Ruby v0.2.0

module JtdCodegenE2e

  class Root0
    attr_accessor :foo

    def self.from_json(data)
      {
        "bar" => RootBar,
        "quux" => RootQuux,
      }[data["foo"]].from_json(data)
    end
  end

  class RootBar < Root0
    attr_accessor :baz

    def self.from_json(data)
      out = RootBar.new
      out.foo = "bar"
      out.baz = JtdCodegenE2e::from_json(String, data["baz"])
      out
    end

    def to_json
      data = { "foo" => "bar" }
      data["baz"] = JtdCodegenE2e::to_json(baz)
      data
    end
  end

  class RootQuux < Root0
    attr_accessor :quuz

    def self.from_json(data)
      out = RootQuux.new
      out.foo = "quux"
      out.quuz = JtdCodegenE2e::from_json(String, data["quuz"])
      out
    end

    def to_json
      data = { "foo" => "quux" }
      data["quuz"] = JtdCodegenE2e::to_json(quuz)
      data
    end
  end

  class Root
    attr_accessor :value

    def self.from_json(data)
      out = Root.new
      out.value = JtdCodegenE2e.from_json(Root0, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  private

  def self.from_json(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type.is_a?(Array)
      data.map { |elem| from_json(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json(type.values.first, elem) }
    else
      type.from_json(data)
    end
  end

  def self.to_json(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(Array)
      data.map { |elem| to_json(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json(elem) }
    else
      data.to_json
    end
  end
end
