// Code generated by jtd-codegen for TypeScript v0.2.1

export enum Root {
  DefaultName = "",
  Foo = "$foo",
  Foo0 = "0foo",
  Foo1 = "_foo",
  FooBar = "foo\nbar",
  FooBar0 = "foo bar",
  Foo0bar = "foo0bar",
  FooBar1 = "foo﷽bar",
}
