// Code generated by jtd-codegen for Rust v0.2.0

pub type Root = String;

pub type DefaultName = String;

pub type Foo = String;

pub type Foo0 = String;

pub type Foo1 = String;

pub type FooBar = String;

pub type FooBar0 = String;

pub type Foo0bar = String;

pub type FooBar1 = String;
