# Code generated by jtd-codegen for Ruby v0.2.0

module JtdCodegenE2e

  class RootNestedIDInitialism
    attr_accessor :json
    attr_accessor :normalword

    def self.from_json(data)
      out = RootNestedIDInitialism.new
      out.json = JtdCodegenE2e::from_json(String, data["json"])
      out.normalword = JtdCodegenE2e::from_json(String, data["normalword"])
      out
    end

    def to_json
      data = {}
      data["json"] = JtdCodegenE2e::to_json(json)
      data["normalword"] = JtdCodegenE2e::to_json(normalword)
      data
    end
  end

  class Root
    attr_accessor :http
    attr_accessor :id
    attr_accessor :nested_id_initialism
    attr_accessor :utf8
    attr_accessor :word_with_embedded_id_initialism
    attr_accessor :word_with_trailing_initialism_id

    def self.from_json(data)
      out = Root.new
      out.http = JtdCodegenE2e::from_json(String, data["http"])
      out.id = JtdCodegenE2e::from_json(String, data["id"])
      out.nested_id_initialism = JtdCodegenE2e::from_json(RootNestedIDInitialism, data["nested_id_initialism"])
      out.utf8 = JtdCodegenE2e::from_json(String, data["utf8"])
      out.word_with_embedded_id_initialism = JtdCodegenE2e::from_json(String, data["word_with_embedded_id_initialism"])
      out.word_with_trailing_initialism_id = JtdCodegenE2e::from_json(String, data["word_with_trailing_initialism_id"])
      out
    end

    def to_json
      data = {}
      data["http"] = JtdCodegenE2e::to_json(http)
      data["id"] = JtdCodegenE2e::to_json(id)
      data["nested_id_initialism"] = JtdCodegenE2e::to_json(nested_id_initialism)
      data["utf8"] = JtdCodegenE2e::to_json(utf8)
      data["word_with_embedded_id_initialism"] = JtdCodegenE2e::to_json(word_with_embedded_id_initialism)
      data["word_with_trailing_initialism_id"] = JtdCodegenE2e::to_json(word_with_trailing_initialism_id)
      data
    end
  end

  private

  def self.from_json(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type.is_a?(Array)
      data.map { |elem| from_json(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json(type.values.first, elem) }
    else
      type.from_json(data)
    end
  end

  def self.to_json(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(Array)
      data.map { |elem| to_json(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json(elem) }
    else
      data.to_json
    end
  end
end
