// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Root {
    #[serde(rename = "notnull_ref_notnull_string")]
    pub notnull_ref_notnull_string: NotnullRefNotnullString,

    #[serde(rename = "notnull_ref_null_string")]
    pub notnull_ref_null_string: NotnullRefNullString,

    #[serde(rename = "notnull_string")]
    pub notnull_string: NotnullString,

    #[serde(rename = "null_ref_notnull_string")]
    pub null_ref_notnull_string: NullRefNotnullString,

    #[serde(rename = "null_ref_null_string")]
    pub null_ref_null_string: NullRefNullString,

    #[serde(rename = "null_string")]
    pub null_string: NullString,
}

pub type NotnullRefNotnullString = NotnullString;

pub type NotnullRefNullString = NullString;

pub type NotnullString = String;

pub type NullRefNotnullString = Option<Box<NotnullString>>;

pub type NullRefNullString = Option<Box<NullString>>;

pub type NullString = Option<Box<String>>;
