// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package jtd_codegen_e2e

type Root string

const (
	Root0 Root = ""

	RootFoo Root = "$foo"

	RootFoo0 Root = "0foo"

	RootFoo1 Root = "_foo"

	RootFooBar Root = "foo\nbar"

	RootFooBar0 Root = "foo bar"

	RootFoo0bar Root = "foo0bar"

	RootFooBar1 Root = "foo﷽bar"
)
