# Code generated by jtd-codegen for Ruby v0.2.0

module JtdCodegenE2e

  class Root
    attr_accessor :notnull_ref_notnull_string
    attr_accessor :notnull_ref_null_string
    attr_accessor :notnull_string
    attr_accessor :null_ref_notnull_string
    attr_accessor :null_ref_null_string
    attr_accessor :null_string

    def self.from_json(data)
      out = Root.new
      out.notnull_ref_notnull_string = JtdCodegenE2e::from_json(NotnullRefNotnullString, data["notnull_ref_notnull_string"])
      out.notnull_ref_null_string = JtdCodegenE2e::from_json(NotnullRefNullString, data["notnull_ref_null_string"])
      out.notnull_string = JtdCodegenE2e::from_json(NotnullString, data["notnull_string"])
      out.null_ref_notnull_string = JtdCodegenE2e::from_json(NullRefNotnullString, data["null_ref_notnull_string"])
      out.null_ref_null_string = JtdCodegenE2e::from_json(NullRefNullString, data["null_ref_null_string"])
      out.null_string = JtdCodegenE2e::from_json(NullString, data["null_string"])
      out
    end

    def to_json
      data = {}
      data["notnull_ref_notnull_string"] = JtdCodegenE2e::to_json(notnull_ref_notnull_string)
      data["notnull_ref_null_string"] = JtdCodegenE2e::to_json(notnull_ref_null_string)
      data["notnull_string"] = JtdCodegenE2e::to_json(notnull_string)
      data["null_ref_notnull_string"] = JtdCodegenE2e::to_json(null_ref_notnull_string)
      data["null_ref_null_string"] = JtdCodegenE2e::to_json(null_ref_null_string)
      data["null_string"] = JtdCodegenE2e::to_json(null_string)
      data
    end
  end

  class NotnullRefNotnullString
    attr_accessor :value

    def self.from_json(data)
      out = NotnullRefNotnullString.new
      out.value = JtdCodegenE2e.from_json(NotnullString, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  class NotnullRefNullString
    attr_accessor :value

    def self.from_json(data)
      out = NotnullRefNullString.new
      out.value = JtdCodegenE2e.from_json(NullString, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  class NotnullString
    attr_accessor :value

    def self.from_json(data)
      out = NotnullString.new
      out.value = JtdCodegenE2e.from_json(String, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  class NullRefNotnullString
    attr_accessor :value

    def self.from_json(data)
      out = NullRefNotnullString.new
      out.value = JtdCodegenE2e.from_json(NotnullString, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  class NullRefNullString
    attr_accessor :value

    def self.from_json(data)
      out = NullRefNullString.new
      out.value = JtdCodegenE2e.from_json(NullString, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  class NullString
    attr_accessor :value

    def self.from_json(data)
      out = NullString.new
      out.value = JtdCodegenE2e.from_json(String, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  private

  def self.from_json(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type.is_a?(Array)
      data.map { |elem| from_json(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json(type.values.first, elem) }
    else
      type.from_json(data)
    end
  end

  def self.to_json(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(Array)
      data.map { |elem| to_json(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json(elem) }
    else
      data.to_json
    end
  end
end
