// Code generated by jtd-codegen for C# + System.Text.Json v0.1.0

using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    public class Root
    {
        [JsonPropertyName("foo")]
        public RootFoo Foo { get; set; }

        [JsonPropertyName("foo_bar")]
        public RootFooBar0 FooBar { get; set; }
    }
}
