// Code generated by jtd-codegen for C# + System.Text.Json v0.2.0

using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    public class Root
    {
        [JsonPropertyName("")]
        public string DefaultName { get; set; }

        [JsonPropertyName("$foo")]
        public string Foo { get; set; }

        [JsonPropertyName("0foo")]
        public string Foo0 { get; set; }

        [JsonPropertyName("_foo")]
        public string Foo1 { get; set; }

        [JsonPropertyName("foo\nbar")]
        public string FooBar { get; set; }

        [JsonPropertyName("foo bar")]
        public string FooBar0 { get; set; }

        [JsonPropertyName("foo0bar")]
        public string Foo0bar { get; set; }

        [JsonPropertyName("foo﷽bar")]
        public string FooBar1 { get; set; }
    }
}
