[package]
name = "jtd_e2e_test"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@segment.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
serde_json = "1.0.83"
serde = { version = "1.0.143", features = ["derive"] }
