// Code generated by jtd-codegen for TypeScript v0.2.1

export interface RootNestedIdInitialism {
  json: string;
  normalword: string;
}

export interface Root {
  http: string;
  id: string;
  nested_id_initialism: RootNestedIdInitialism;
  utf8: string;
  word_with_embedded_id_initialism: string;
  word_with_trailing_initialism_id: string;
}
