// Code generated by jtd-codegen for TypeScript v0.2.1

export type Root = RootBarBaz | RootQuux;

export interface RootBarBaz {
  foo: "BAR_BAZ";
  baz: string;
}

export interface RootQuux {
  foo: "QUUX";
  quuz: string;
}
