# Code generated by jtd-codegen for Ruby v0.1.1

require 'json'
require 'time'

module JTDCodegenE2E

  class Root
    attr_accessor :bar
    attr_accessor :baz
    attr_accessor :foo

    def self.from_json_data(data)
      out = Root.new
      out.bar = JTDCodegenE2E::from_json_data(Array[String], data["bar"])
      out.baz = JTDCodegenE2E::from_json_data(TrueClass, data["baz"])
      out.foo = JTDCodegenE2E::from_json_data(String, data["foo"])
      out
    end

    def to_json_data
      data = {}
      data["bar"] = JTDCodegenE2E::to_json_data(bar) unless bar.nil?
      data["baz"] = JTDCodegenE2E::to_json_data(baz) unless baz.nil?
      data["foo"] = JTDCodegenE2E::to_json_data(foo) unless foo.nil?
      data
    end
  end

  private

  def self.from_json_data(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type == DateTime
      DateTime.rfc3339(data)
    elsif type.is_a?(Array)
      data.map { |elem| from_json_data(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json_data(type.values.first, elem) }
    else
      type.from_json_data(data)
    end
  end

  def self.to_json_data(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(DateTime)
      data.rfc3339
    elsif data.is_a?(Array)
      data.map { |elem| to_json_data(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json_data(elem) }
    else
      data.to_json_data
    end
  end
end
