// Code generated by jtd-codegen for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    [JsonConverter(typeof(NotnullRefNotnullStringJsonConverter))]
    public class NotnullRefNotnullString
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public NotnullString Value { get; set; }
    }

    public class NotnullRefNotnullStringJsonConverter : JsonConverter<NotnullRefNotnullString>
    {
        public override NotnullRefNotnullString Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new NotnullRefNotnullString { Value = JsonSerializer.Deserialize<NotnullString>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, NotnullRefNotnullString value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<NotnullString>(writer, value.Value, options);
        }
    }
}
