// Code generated by jtd-codegen for C# + System.Text.Json v0.1.0

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    [JsonConverter(typeof(NullRefNullStringJsonConverter))]
    public class NullRefNullString
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public NullString? Value { get; set; }
    }

    public class NullRefNullStringJsonConverter : JsonConverter<NullRefNullString>
    {
        public override NullRefNullString Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new NullRefNullString { Value = JsonSerializer.Deserialize<NullString?>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, NullRefNullString value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<NullString?>(writer, value.Value, options);
        }
    }
}
