# Code generated by jtd-codegen for Ruby v0.2.0

module JtdCodegenE2e

  class Root
    attr_accessor :foo

    def self.from_json(data)
      {
        "bar" => RootBar,
      }[data["foo"]].from_json(data)
    end
  end

  class RootBar < Root
    attr_accessor :baz
    attr_accessor :quux

    def self.from_json(data)
      out = RootBar.new
      out.foo = "bar"
      out.baz = JtdCodegenE2e::from_json(Array[String], data["baz"])
      out.quux = JtdCodegenE2e::from_json(TrueClass, data["quux"])
      out
    end

    def to_json
      data = { "foo" => "bar" }
      data["baz"] = JtdCodegenE2e::to_json(baz) unless baz.nil?
      data["quux"] = JtdCodegenE2e::to_json(quux) unless quux.nil?
      data
    end
  end

  private

  def self.from_json(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type.is_a?(Array)
      data.map { |elem| from_json(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json(type.values.first, elem) }
    else
      type.from_json(data)
    end
  end

  def self.to_json(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(Array)
      data.map { |elem| to_json(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json(elem) }
    else
      data.to_json
    end
  end
end
