// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    public class RootFooBar0
    {
        [JsonPropertyName("x")]
        public string X { get; set; }
    }
}
