// Code generated by jtd-codegen for C# + System.Text.Json v0.2.0

using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    public class RootFoo
    {
        [JsonPropertyName("bar")]
        public RootFooBar Bar { get; set; }
    }
}
