// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum Root {
    @JsonProperty("Bar")
    BAR,

    @JsonProperty("Baz")
    BAZ,

    @JsonProperty("Foo")
    FOO,
}
