# Code generated by jtd-codegen for Ruby v0.2.0

module JtdCodegenE2e

  # A description for discriminator
  class RootDiscriminatorWithDescription
    attr_accessor :foo

    def self.from_json(data)
      {
        "bar" => RootDiscriminatorWithDescriptionBar,
      }[data["foo"]].from_json(data)
    end
  end

  # A description for discriminator variant
  class RootDiscriminatorWithDescriptionBar < RootDiscriminatorWithDescription

    def self.from_json(data)
      out = RootDiscriminatorWithDescriptionBar.new
      out.foo = "bar"
      out
    end

    def to_json
      data = { "foo" => "bar" }
      data
    end
  end

  # A description for enum
  class RootEnumWithDescription
    attr_accessor :value

    def initialize(value)
      self.value = value
    end

    private_class_method :new

    # A description for X
    X = new("X")

    # A description for Y
    Y = new("Y")

    # A description for Z
    Z = new("Z")

    def self.from_json(data)
      {
        "X" => X,
        "Y" => Y,
        "Z" => Z,
      }[data]
    end

    def to_json
      value
    end
  end

  # A description for properties
  class RootPropertiesWithDescription

    def self.from_json(data)
      out = RootPropertiesWithDescription.new
      out
    end

    def to_json
      data = {}
      data
    end
  end

  class Root
    # A description for discriminator
    attr_accessor :discriminator_with_description

    # A description for enum
    attr_accessor :enum_with_description

    # Whereas disregard and contempt for human rights have resulted in barbarous
    # acts which have outraged the conscience of mankind, and the advent of a
    # world in which human beings shall enjoy freedom of speech and belief and
    # freedom from fear and want has been proclaimed as the highest aspiration
    # of the common people,
    attr_accessor :long_description

    # A description for properties
    attr_accessor :properties_with_description

    # A description for ref
    attr_accessor :ref_with_description

    # A description for string
    attr_accessor :string_with_description

    def self.from_json(data)
      out = Root.new
      out.discriminator_with_description = JtdCodegenE2e::from_json(RootDiscriminatorWithDescription, data["discriminator_with_description"])
      out.enum_with_description = JtdCodegenE2e::from_json(RootEnumWithDescription, data["enum_with_description"])
      out.long_description = JtdCodegenE2e::from_json(String, data["long_description"])
      out.properties_with_description = JtdCodegenE2e::from_json(RootPropertiesWithDescription, data["properties_with_description"])
      out.ref_with_description = JtdCodegenE2e::from_json(Baz, data["ref_with_description"])
      out.string_with_description = JtdCodegenE2e::from_json(String, data["string_with_description"])
      out
    end

    def to_json
      data = {}
      data["discriminator_with_description"] = JtdCodegenE2e::to_json(discriminator_with_description)
      data["enum_with_description"] = JtdCodegenE2e::to_json(enum_with_description)
      data["long_description"] = JtdCodegenE2e::to_json(long_description)
      data["properties_with_description"] = JtdCodegenE2e::to_json(properties_with_description)
      data["ref_with_description"] = JtdCodegenE2e::to_json(ref_with_description)
      data["string_with_description"] = JtdCodegenE2e::to_json(string_with_description)
      data
    end
  end

  # A description for a definition
  class Baz
    attr_accessor :value

    def self.from_json(data)
      out = Baz.new
      out.value = JtdCodegenE2e.from_json(String, data)
      out
    end

    def to_json
      JtdCodegenE2e.to_json(value)
    end
  end

  private

  def self.from_json(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type.is_a?(Array)
      data.map { |elem| from_json(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json(type.values.first, elem) }
    else
      type.from_json(data)
    end
  end

  def self.to_json(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(Array)
      data.map { |elem| to_json(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json(elem) }
    else
      data.to_json
    end
  end
end
