// Code generated by jtd-codegen for Java + Jackson v0.1.0

package com.example;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum RootOverrideTypeEnum {
    @JsonProperty("BAR")
    BAR,

    @JsonProperty("FOO")
    FOO,
}
