# Code generated by jtd-codegen for Ruby v0.1.1

require 'json'
require 'time'

module JTDCodegenE2E

  class RootOverrideTypeDiscriminatorBaz < Object

    def self.from_json_data(data)
      out = RootOverrideTypeDiscriminatorBaz.new
      out.foo = "baz"
      out
    end

    def to_json_data
      data = { "foo" => "baz" }
      data
    end
  end

  class Root
    attr_accessor :override_elements_container
    attr_accessor :override_type_discriminator
    attr_accessor :override_type_enum
    attr_accessor :override_type_expr
    attr_accessor :override_type_properties
    attr_accessor :override_values_container

    def self.from_json_data(data)
      out = Root.new
      out.override_elements_container = JTDCodegenE2E::from_json_data(Array[String], data["override_elements_container"])
      out.override_type_discriminator = JTDCodegenE2E::from_json_data(Object, data["override_type_discriminator"])
      out.override_type_enum = JTDCodegenE2E::from_json_data(Object, data["override_type_enum"])
      out.override_type_expr = JTDCodegenE2E::from_json_data(Object, data["override_type_expr"])
      out.override_type_properties = JTDCodegenE2E::from_json_data(Object, data["override_type_properties"])
      out.override_values_container = JTDCodegenE2E::from_json_data(Hash[String, String], data["override_values_container"])
      out
    end

    def to_json_data
      data = {}
      data["override_elements_container"] = JTDCodegenE2E::to_json_data(override_elements_container)
      data["override_type_discriminator"] = JTDCodegenE2E::to_json_data(override_type_discriminator)
      data["override_type_enum"] = JTDCodegenE2E::to_json_data(override_type_enum)
      data["override_type_expr"] = JTDCodegenE2E::to_json_data(override_type_expr)
      data["override_type_properties"] = JTDCodegenE2E::to_json_data(override_type_properties)
      data["override_values_container"] = JTDCodegenE2E::to_json_data(override_values_container)
      data
    end
  end

  private

  def self.from_json_data(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type == DateTime
      DateTime.rfc3339(data)
    elsif type.is_a?(Array)
      data.map { |elem| from_json_data(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json_data(type.values.first, elem) }
    else
      type.from_json_data(data)
    end
  end

  def self.to_json_data(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(DateTime)
      data.rfc3339
    elsif data.is_a?(Array)
      data.map { |elem| to_json_data(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json_data(elem) }
    else
      data.to_json_data
    end
  end
end
