// Code generated by jtd-codegen for TypeScript v0.2.1

export interface Root {
  "": string;
  $foo: string;
  "0foo": string;
  _foo: string;
  "foo\nbar": string;
  "foo bar": string;
  foo0bar: string;
  "foo﷽bar": string;
}
