# Code generated by jtd-codegen for Ruby v0.2.0

module JtdCodegenE2e

  class Root
    attr_accessor :foo

    def self.from_json(data)
      {
        "BAR_BAZ" => RootBarBaz,
        "QUUX" => RootQuux,
      }[data["foo"]].from_json(data)
    end
  end

  class RootBarBaz < Root
    attr_accessor :baz

    def self.from_json(data)
      out = RootBarBaz.new
      out.foo = "BAR_BAZ"
      out.baz = JtdCodegenE2e::from_json(String, data["baz"])
      out
    end

    def to_json
      data = { "foo" => "BAR_BAZ" }
      data["baz"] = JtdCodegenE2e::to_json(baz)
      data
    end
  end

  class RootQuux < Root
    attr_accessor :quuz

    def self.from_json(data)
      out = RootQuux.new
      out.foo = "QUUX"
      out.quuz = JtdCodegenE2e::from_json(String, data["quuz"])
      out
    end

    def to_json
      data = { "foo" => "QUUX" }
      data["quuz"] = JtdCodegenE2e::to_json(quuz)
      data
    end
  end

  private

  def self.from_json(type, data)
    if data.nil? || [Object, TrueClass, Integer, Float, String].include?(type)
      data
    elsif type.is_a?(Array)
      data.map { |elem| from_json(type.first, elem) }
    elsif type.is_a?(Hash)
      data.transform_values { |elem| from_json(type.values.first, elem) }
    else
      type.from_json(data)
    end
  end

  def self.to_json(data)
    if data.nil? || [TrueClass, FalseClass, Integer, Float, String].include?(data.class)
      data
    elsif data.is_a?(Array)
      data.map { |elem| to_json(elem) }
    elsif data.is_a?(Hash)
      data.transform_values { |elem| to_json(elem) }
    else
      data.to_json
    end
  end
end
