// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize)]
pub struct RootOverrideTypeDiscriminatorBaz {}

#[derive(Serialize, Deserialize)]
pub struct Root {
    #[serde(rename = "override_elements_container")]
    pub override_elements_container: Vec<String>,

    #[serde(rename = "override_type_discriminator")]
    pub override_type_discriminator: serde_json::Value,

    #[serde(rename = "override_type_enum")]
    pub override_type_enum: serde_json::Value,

    #[serde(rename = "override_type_expr")]
    pub override_type_expr: serde_json::Value,

    #[serde(rename = "override_type_properties")]
    pub override_type_properties: serde_json::Value,

    #[serde(rename = "override_values_container")]
    pub override_values_container: HashMap<String, String>,
}
