// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    /// <summary>
    /// For type "Polygon", the "coordinates" member MUST be an array of
    /// linear ring coordinate arrays.
    /// </summary>
    public class GeojsonObjectPolygon : GeojsonObject
    {
        [JsonPropertyName("type")]
        public string Type_ { get => "Polygon"; }

        [JsonPropertyName("coordinates")]
        public IList<LinearRing> Coordinates { get; set; }

        [JsonPropertyName("bbox")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public BoundingBox? Bbox { get; set; }
    }
}
