// Code generated by jtd-codegen for C# + System.Text.Json v0.1.0

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    /// <summary>
    /// For type "LineString", the "coordinates" member is an array of two
    /// or more positions.
    /// </summary>
    public class GeojsonObjectLineString : GeojsonObject
    {
        [JsonPropertyName("type")]
        public string Type_ { get => "LineString"; }

        [JsonPropertyName("coordinates")]
        public IList<Position> Coordinates { get; set; }

        [JsonPropertyName("bbox")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public BoundingBox? Bbox { get; set; }
    }
}
