// Code generated by jtd-codegen for Go v0.1.0. DO NOT EDIT.

package jtd_codegen_e2e

type Root struct {
	For For `json:"for"`

	Object Object `json:"object"`
}

type For = string

type Object = string
