// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace JtdCodegenE2E
{
    /// <summary>
    /// A description for properties
    /// </summary>
    public class RootPropertiesWithDescription
    {
    }
}
