// Code generated by jtd-codegen for Go v0.1.0. DO NOT EDIT.

package jtd_codegen_e2e

type Root0 struct {
	Bar string `json:"bar"`

	Baz []bool `json:"baz"`

	Foo bool `json:"foo"`

	Quux []bool `json:"quux"`
}

type Root = *Root0
