on: push
jobs:
  test:
    strategy:
      matrix:
        package:
          - jtd_codegen_cli
          - jtd_codegen_target_csharp_system_text
          - jtd_codegen_target_go
          - jtd_codegen_target_java_jackson
          - jtd_codegen_target_python
          - jtd_codegen_target_ruby
          - jtd_codegen_target_ruby_sig
          - jtd_codegen_target_rust
          - jtd_codegen_target_typescript
          - jtd_codegen_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --package=$PACKAGE
        env:
          PACKAGE: ${{ matrix.package }}
